version: "3.8"

services:
  chickadee-db:
    image: mcr.microsoft.com/azure-sql-edge

    ports:
      - "1433:1433"
    restart: always

    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: SqlPassword!

  chickadee:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - chickadee-db
    ports:
      - "8888:80"
    restart: always
    environment:
      - DBHOST=chickadee-db
      - DBPORT=1433
      - DBUSER=sa
      - DBPASSWORD=SqlPassword!
      - DBNAME=chickadee
      - ASPNETCORE_ENVIRONMENT=Development
